image: anchormen/debian-sbt

cache:
  paths:
    - "~/.ivy2"
    - "~/.sbt"

stages:
  - test
  - package

test:
  stage: test
  only:
    - develop
    - master
  script:
    - "$SBT_HOME/bin/sbt -Dsbt.global.base=~/.sbt -Dsbt.ivy.home=~/.ivy2 -Dsbt.log.noformat=true +test"

package:
  stage: package
  only:
    - develop
    - master
  script:
    - "$SBT_HOME/bin/sbt -Dsbt.global.base=~/.sbt -Dsbt.ivy.home=~/.ivy2 -Dsbt.log.noformat=true +publish"
  artifacts:
    expire_in: 1 week
    paths:
      - "target/scala-2.11/*.jar"
      - "target/scala-2.12/*.jar"
