language: scala
sudo: false
scala:
- 2.12.4
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sbt"
  - "$HOME/.ivy2"
sudo: true
scala:
    - 2.12.4
jdk:
    - oraclejdk8
before_install:
    - gem install rubygems-update
    - update_rubygems
    - gem update --system
cache:
    directories:
        - "$HOME/.m2/repository"
        - "$HOME/.sbt"
        - "$HOME/.ivy2"
deploy:
    on:
        all_branches: true
    dry-run: true
    provider: bintray
    key:
        secure: CSKDE8sH87LiE2ByyB6N0M5pgFWk2gv3V+NVsqAVh+LG6W304IFLkVpQYf7ZjSLXRopHsVnfefI4STvHtvVLrK89fuNo3XAfvdCK6YJMtoVMLiI4476eAxJuVd9elt9JqsYk5cqBwZNmKVLkXxoWVSem1NHuZg8jC1yYpxuPWbv7DwNd+CmAI6KJJWu1lquSxYvcJ6/P+QXPRvwA785CAMQOk4dWyliAyRcfOMgEU6HNRrFIjhMz4iWtZS5JlErR2syul6Jdchrpd3776faQoXV+bw3m0o1aL+j4m/H3BDOgM2yMzsMkCvqkt+4U2h66mHXycSuZSvMYSVWRq7A/ixkH8vaWVluE9XjmQ1spKjzIRIHM9B6fZ6Gxf5eQiA+JlIXCokDFwxHEPZQKMYpsss0Iw8fy7KgPC5Fp3e28jPllyv51pCUDOwJ160AH6Vswbh3y3KmdQoP/hwdHIunKxEZHvPw29hGYN6dffPEwkj1okM/Vkgzl1Iv7UwFhqbw9KdcYWCrYZBT2ByEFjgG/u2PVmUu3Gd8n1nBoI4vWxpVGhDnFvJXxhCCgTXAvCmvYkd00SyUGO4VEAnIjheA7xHNSppAFH0bjo+wQPcvI4DWS4HMiIFKBkOTL3kp6mKqV2nYTcCLXqdQemWrZLgZ+675vnARsnOnTSoMVeXcILAU=
