language: scala
scala:
    - 2.12.4
jdk:
    - oraclejdk8
cache:
    directories:
        - "$HOME/.m2/repository"
        - "$HOME/.sbt"
        - "$HOME/.ivy2"
jobs:
    include:
        - stage: test
        - stage: deploy
          if: branch = master
          install: skip
          script: "sbt ++$TRAVIS_SCALA_VERSION publish"
