language: scala
scala:
    - 2.12.4
jdk:
    - oraclejdk8
cache:
    directories:
        - "$HOME/.m2/repository"
        - "$HOME/.sbt"
        - "$HOME/.ivy2"
deploy:
    file: travis-ci/descriptor.json
    provider: bintray
    key: 0b189a6348a342a4a226dd0b94281ec7367581a4
    on:
        all_branches: true
