language: scala
scala:
    - 2.12.4
jdk:
    - oraclejdk8
cache:
    directories:
        - "$HOME/.m2/repository"
        - "$HOME/.sbt"
        - "$HOME/.ivy2"
deploy:
    file: travis-ci/descriptor.json
    provider: bintray
    key:
        secure: "5EbIt0qdkIFD6zYiOQi/6MfSDDcqRPoJ4rDdo+yHGlc9bIa+BFHn7AyoI4aDGoxAA8zKoLIFKjHGdduodPF4EoSlU8VkCbs64NxhAIzIKczFC9oJdnpBEjLBdBjYFOyKa74QqAr3+93D33LKvHiljaIYj917zen3w2WGrorwU8KhSgZaIYNwtNaHlM+eb0LbIB9icB7AATew1l8VOeHrewL813cv+/bUfqMmmqoF2Svoqoirvxm4sxhKqloIUdNoH7hFObKBChmWAesI1H/Ond+A8JmhKKrQ4B4jc295QY+PX8kguZcIPOqKah9WejJBLsXy0jCoJxhbbgPTkBOeu5/kickWOIJEoqko8Z5jNJRKwkoHTvHlzF/qRNa11S5LbiTE7ymc2p/kVkcvqd7G7bo6Coobdb9OQCcKroT51eiIyRxwpltvHf5rQucT5B8yC9/gbgVQLLeq6LXy2bZwjrmNsk28GNJnrf3gY9ruGrLpwoEcFm/q82tTq1JSySqNBdbrnRDuYb7ku534iQstlXD+l3o1xSFdT8IsfCYLWKekiMserfsyXMoZheHljZk9WXy+E0IIj7crzPaq7NRU+G8h94bJ1fRimgKmF77QXnWz3BvkjeqX9ABNpo6VD7PIWE24nHq06Nb7xZHVmuETSr6UvylRDD7gGsyG9mCbqxA="
    on:
        all_branches: true
